import type { Theme } from '@emotion/react';

const baseThemeCommonTokens = {
  fontFamily: [
    "'Work Sans'",
    '-apple-system',
    'BlinkMacSystemFont',
    "'Segoe UI'",
    'Helvetica',
    "'Apple Color Emoji'",
    'Arial',
    'sans-serif',
    "'Segoe UI Emoji'",
  ],
  fontSize: '1em',
  buttonPrimaryShadow: '0px 0px 0px 0px #ffffff00',
  buttonPrimaryHoverShadow: '0px 0px 0px 0px #ffffff00',
  buttonPrimaryActiveShadow: '0px 0px 0px 0px #ffffff00',
  buttonPrimaryBorder: '0 none',
  buttonSecondaryShadow: '0px 0px 0px 0px #ffffff00',
  buttonSecondaryHoverShadow: '0px 0px 0px 0px #ffffff00',
  buttonSecondaryActiveShadow: '0px 0px 0px 0px #ffffff00',
  buttonSecondaryBorder: '0 none',
  buttonDisabledBorder: '0 none',
  overlayBackdropFilter: 'blur(0px)',
  drawerBorderRadius: '20px 20px 0 0',
  modalBorderRadius: 20,
  modalShadow: '0px 0px 0px 0px #ffffff00',
};

export const tantoDarkTheme: Theme = {
  mode: 'dark',
  buttonPrimaryBackground: '#F1F3F9',
  buttonPrimaryColor: '#15181E',
  buttonPrimaryHoverBackground: '#CDD5E5',
  buttonPrimaryHoverColor: '#15181E',
  buttonPrimaryActiveBackground: '#F1F3F9',
  buttonPrimaryActiveColor: '#15181E',
  buttonSecondaryBackground: '#CDD5E512',
  buttonSecondaryColor: '#F1F3F9',
  buttonSecondaryHoverBackground: '#CDD5E51A',
  buttonSecondaryHoverColor: '#15181E',
  buttonSecondaryActiveBackground: '#CDD5E526',
  buttonSecondaryActiveColor: '#15181E',
  buttonDisabledBackground: '#CDD5E512',
  buttonDisabledColor: 'rgba(205, 213, 229, 0.7)',
  bodyText: '#fff',
  mutedText: 'rgba(205, 213, 229, 0.75)',
  overlayBackground: 'rgba(12, 12, 13, 0.6)',
  modalBackground: '#15181E',
  modalColor: '#fff',
  modalBorder: '1px solid #272B34',
  spinnerColor: '#f1f3f9',
  skeletonColor: 'rgba(205, 213, 229, 0.07)',
  scrollbarTrack: '#15181E',
  scrollbarThumb: '#353a45',
  linkColor: '#5294F8',
  dividerBorder: '1px dashed #353A45',
  listItemBackground: 'rgba(205, 213, 229, 0.07)',
  listItemHoverBackground: 'rgba(205, 213, 229, 0.1)',
  ...baseThemeCommonTokens,
};

export const tantoLightTheme: Theme = {
  mode: 'light',
  buttonPrimaryBackground: '#000',
  buttonPrimaryColor: '#fff',
  buttonPrimaryHoverBackground: '#4B5563',
  buttonPrimaryHoverColor: '#fff',
  buttonPrimaryActiveBackground: '#374151',
  buttonPrimaryActiveColor: '#fff',
  buttonSecondaryBackground: 'rgba(0, 0, 0, 0.05)',
  buttonSecondaryColor: '#000',
  buttonSecondaryHoverBackground: '#E5E7EB',
  buttonSecondaryHoverColor: '#000',
  buttonSecondaryActiveBackground: '#D1D5DB',
  buttonSecondaryActiveColor: '#000',
  buttonDisabledBackground: '#E5E7EB',
  buttonDisabledColor: '#9CA3AF',
  bodyText: '#000',
  mutedText: 'rgba(103, 89, 89, 0.75)',
  overlayBackground: 'rgba(12, 12, 13, 0.8)',
  modalBackground: '#FFFFFF',
  modalColor: '#000',
  modalBorder: '1px solid #272B34',
  spinnerColor: '#4B5563',
  skeletonColor: 'rgba(0, 0, 0, 0.03)',
  scrollbarTrack: '#F9FAFB',
  scrollbarThumb: '#D1D5DB',
  linkColor: '#1D4ED8',
  dividerBorder: '1px dashed #D1D5DB',
  listItemBackground: 'transparent',
  listItemHoverBackground: 'rgba(0, 0, 0, 0.05)',
  ...baseThemeCommonTokens,
};
