export const baseThemeTokens = {
  fontFamily: [
    "'Work Sans'",
    '-apple-system',
    'BlinkMacSystemFont',
    "'Segoe UI'",
    'Helvetica',
    "'Apple Color Emoji'",
    'Arial',
    'sans-serif',
    "'Segoe UI Emoji'",
  ],
  fontSize: 16,
  buttonPrimaryShadow: 'none',
  buttonPrimaryHoverShadow: 'none',
  buttonPrimaryActiveShadow: 'none',
  buttonPrimaryBorder: '0 none',
  buttonSecondaryShadow: 'none',
  buttonSecondaryHoverShadow: 'none',
  buttonSecondaryActiveShadow: 'none',
  buttonSecondaryBorder: '0 none',
  buttonDisabledBorder: '0 none',
  overlayBackdropFilter: 'none',
  drawerBorderRadius: '20px 20px 0 0',
  modalBorderRadius: 20,
  modalShadow: 'none',
};
