export type { TantoConnectButtonProps } from './ConnectButton';
export { TantoConnectButton } from './ConnectButton';
export type { TantoProviderProps } from './contexts/tanto/TantoProvider';
export { TantoProvider } from './contexts/tanto/TantoProvider';
export type { TantoEmbeddedWidgetProps } from './EmbeddedWidget';
export { TantoEmbeddedWidget } from './EmbeddedWidget';
export type { AppMetadata, DefaultConfig, KeylessWalletConfig } from './getDefaultConfig';
export { createConnectors, createTransports, getDefaultConfig, RONIN_WALLET_METADATA } from './getDefaultConfig';
export { useConnectedWallet } from './hooks/useConnectedWallet';
export type { UseRnsAddressParameters } from './hooks/useRnsAddress';
export { useRnsAddress } from './hooks/useRnsAddress';
export type { UseRnsNameParameters } from './hooks/useRnsName';
export { useRnsName } from './hooks/useRnsName';
export { useWidgetModal as useTantoModal } from './hooks/useWidgetModal';
export { tantoDarkTheme, tantoLightTheme } from './styles/theme';
export type { TantoWidgetCustomTheme, TantoWidgetTheme } from './types/theme';
