export type { TantoConnectButtonProps } from './ConnectButton';
export { TantoConnectButton } from './ConnectButton';
export type { TantoProviderProps } from './contexts/tanto/TantoProvider';
export { TantoProvider } from './contexts/tanto/TantoProvider';
export type { TantoEmbeddedWidgetProps } from './EmbeddedWidget';
export { TantoEmbeddedWidget } from './EmbeddedWidget';
export { getDefaultConfig } from './getDefaultConfig';
export { useConnectedWallet } from './hooks/useConnectedWallet';
export { useWidgetModal as useTantoModal } from './hooks/useWidgetModal';
export { tantoDarkTheme, tantoLightTheme } from './styles/theme';
export type { WidgetTheme } from './types/theme';
